# Generated by Django 4.2.6 on 2023-10-21 03:31

from django.db import migrations
import requests

def add_initial_data(apps, schema_editor):
    District = apps.get_model('app', 'District')
    DistrictTemperature = apps.get_model('app', 'DistrictTemperature')
    districts = District.objects.all()
    for d in districts:
        response = requests.get(f'https://api.open-meteo.com/v1/forecast?latitude={d.lat}&longitude={d.long}&hourly=temperature_2m')
        weather_data = response.json()
        
        total_temperature = 0
        count = 0
        district_temperature_list = []
        for i in range(14, 7 * 24, 24):
            district_temperature_list.append(DistrictTemperature(district=d,date=weather_data['hourly']['time'][i],temp=weather_data['hourly']['temperature_2m'][i]))
            total_temperature += weather_data['hourly']['temperature_2m'][i]
            count += 1
        DistrictTemperature.objects.bulk_create(district_temperature_list)
        average_temperature = total_temperature / count
        d.avg_temp = average_temperature
        d.save()
    
    
class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_districttemperature'),
    ]

    operations = [
         migrations.RunPython(add_initial_data),
    ]
